require('bare-abort-controller/global')
require('bare-crypto/global')
require('bare-encoding/global')
require('bare-events/global')
require('bare-fetch/global')
require('bare-process/global')
require('bare-stream/global')
